### ISSUE TITLE
Missing machining files for 2020 clear lid?

### ISSUE THREAD

**Issue by cscott** [OpenEVSE/Enclosures#2]
I was thinking of adding a keypad to the front of my OpenEVSE box, and was looking for the dimensions of the stock lid. f5915763a12c14ccf67352120ec5695f42bb7406 is very helpful and shows the case manufacturer (polycase ML-58, so I can get a new lid at https://www.polycase.com/ml-58f, but apparently only as part of the full case, I can't get a lid by itself, alas).  However, the current OpenEVSE lid appears to have mounting features for the LCD molded in (see https://openevse.dozuki.com/Guide/Current+-+v5.5+OpenEVSE+Advanced+and+Value/26#s204 ) but the drawings for that feature arein't included in the Enclosures repository.  Obviously it would be helpful to know the exact positioning and location of the LCD mounting holes so I could duplicate them in my semi-custom lid-with-keypad.  Thanks!

**Comment by cscott** [comment]
Actually, it looks like in my older OpenEVSE unit there was some sort of clear acyrlic mount of some kind, but in my newer OpenEVSE box the LCD mount appears to be 3d printed.  If you could add the 3d files for the LCD mount (STEP or STL?) to this repo that would also work/be helpful.

**Comment by chris1howell** [comment]
The STL models for the LCD mount and positioning Jig have been uploaded. [36b0d13](https://github.com/OpenEVSE/Enclosures/commit/36b0d13bee819f67ae085a60301c6bb307e585a9)

**Comment by cscott** [comment]
Thank you so much!  You rock.

**Comment by cscott** [comment]
(For clarity to anyone who stumbles upon this in the future -- it looks like the clear lids aren't machined by Polycase, but instead a mounting insert was glued to the inside of the lid.  One of my OpenEVSE boxes has a clear acrylic mount, apparently machines from a rectangle of 1/4" sheet acrylic? -- and the other has the 3d printed mount uploaded here.  It looks like the positioning jig helps glue this in the proper place on the inside of the lid, so it lines up with the opening in the printed artwork printed by polycase on the lid.)

**Comment by chris1howell** [comment]
The 3D printed part is welded on with a solvent. It basically melts the two
parts into one. Here is what we use. Be sure to have proper ventilation.

https://lustercraft.com/product/weld-on-16-acrylic-solvent-cement/?attribute_size=1.5+oz.+tube&gclid=CjwKCAiA_vKeBhAdEiwAFb_nrfoEu7bwt5eZXy6ktdrMP4B4C4me8z035jT3aBPZwEKoU4VdsIAyBxoCYSYQAvD_BwE
